add validator
nantonov/AKD pull request #25
Opened 2022-11-03 14:59 UTC by kaallaash

2022-11-03 15:04 UTC, moltenessence requested changes

2022-11-03 15:04 UTC, moltenessence commented on DescriptiveGeometry/DG.API/Controllers/DrawingController.cs
> +                .ValidateAsync(changeDrawingViewModel, cancellationToken);
You can use ValidateAndThrowAsync to get rid of your extensions

2022-11-04 10:00 UTC, Blackolf931 requested changes

2022-11-04 10:00 UTC, Blackolf931 commented on DescriptiveGeometry/DG.API/Validators/ChangeDrawingViewModelValidator.cs
> +        RuleFor(d => d.Description).NotNull();
Is a string consisting of spaces processed here?

2022-11-04 10:02 UTC, kaallaash commented on DescriptiveGeometry/DG.API/Controllers/DrawingController.cs
> +            .ValidateAndThrowAsync(changeDrawingViewModel, cancellationToken)
my fail

2022-11-04 11:07 UTC, moltenessence requested changes
Check out your ci/cd, one test doesn't pass

2022-11-04 11:14 UTC, kaallaash commented
> Check out your ci/cd, one test doesn't pass

I did hotfix PR for it. https://github.com/nantonov/AKD/pull/26

2022-11-07 12:20 UTC, nantonov approved these changes

2022-11-07 13:29 UTC, stas1408123 approved these changes

2022-11-07 13:30 UTC, moltenessence approved these changes

2022-11-07 13:30 UTC, merged