Feature/add api tests
nantonov/AKD pull request #27
Opened 2022-11-07 12:31 UTC by kaallaash

2022-11-07 13:19 UTC, Blackolf931 requested changes

2022-11-07 13:19 UTC, Blackolf931 commented on DescriptiveGeometry/Tests/DG.API.Tests/DrawingControllerTests.cs
> +                await client.GetFromJsonAsync<DrawingViewModel>($"/api/drawing/{validDrawingEntity.Id}");
move to constants '/api/drawing/' in each case

2022-11-07 13:19 UTC, Blackolf931 commented on DescriptiveGeometry/Tests/DG.API.Tests/DrawingControllerTests.cs
> +        }
Add Ensure deleted in the end of method

2022-11-07 14:12 UTC, Blackolf931 approved these changes

2022-11-08 07:09 UTC, Blackolf931 approved these changes

2022-11-08 12:43 UTC, GodlyCat approved these changes

2022-11-08 12:49 UTC, merged