add DAL tests
nantonov/AKD pull request #29
Opened 2022-11-08 15:20 UTC by kaallaash

2022-11-09 10:20 UTC, Blackolf931 requested changes

2022-11-09 10:20 UTC, Blackolf931 commented on DescriptiveGeometry/Tests/DG.DAL.Tests/DrawingRepositoryTests.cs
> +        Assert.NotNull(drawing);
Do investigation about Shouldly, and use it

2022-11-09 10:20 UTC, Blackolf931 commented on DescriptiveGeometry/Tests/DG.DAL.Tests/DrawingRepositoryTests.cs
> +        var drawing = await _drawingRepository.GetById(ValidDrawingEntity.Id + 1, default);
You can use int.max or something like that instead of `ValidDrawingEntity.Id + 1`

2022-11-09 10:20 UTC, Blackolf931 commented on DescriptiveGeometry/Tests/DG.DAL.Tests/DrawingRepositoryTests.cs
> +            await _drawingRepository.Create(validEntity, default);
you can use _context.TableName.AddRange instead of loop

2022-11-09 10:41 UTC, nantonov requested changes

2022-11-09 10:41 UTC, nantonov commented on DescriptiveGeometry/Tests/DG.DAL.Tests/DrawingRepositoryTests.cs
> +public class DrawingRepositoryTests
This is not just a test, it's certain integration test

2022-11-09 10:41 UTC, nantonov commented on DescriptiveGeometry/Tests/DG.DAL.Tests/DrawingRepositoryTests.cs
> +namespace DG.DAL.Tests;
Should be IntegrationTests?

2022-11-09 10:41 UTC, nantonov commented on DescriptiveGeometry/Tests/DG.DAL.Tests/DrawingRepositoryTests.cs
> +            Assert.True(false);
Strange
If you expect exception, you should assert that exception was thrown

2022-11-09 10:41 UTC, nantonov commented on DescriptiveGeometry/Tests/DG.DAL.Tests/DrawingRepositoryTests.cs
> +    public async Task Delete_ValidId_ReturnsOK()
Who returns OK?

2022-11-09 10:41 UTC, nantonov commented on DescriptiveGeometry/Tests/DG.DAL.Tests/DrawingRepositoryTests.cs
> +        await _context.Database.EnsureDeletedAsync();
Do not duplicate this line in each test

2022-11-09 10:41 UTC, nantonov commented on DescriptiveGeometry/Tests/DG.DAL.Tests/DrawingRepositoryTests.cs
> +    public async Task Delete_InvalidId_ReturnsException()
We cannot return an exception

2022-11-09 10:41 UTC, nantonov commented on DescriptiveGeometry/Tests/DG.DAL.Tests/DrawingRepositoryTests.cs
> +        await _drawingRepository.Create(ValidDrawingEntity, default);
Don't use repository which you want to test to seed data for testing..

2022-11-09 10:41 UTC, nantonov commented on DescriptiveGeometry/Tests/DG.DAL.Tests/DrawingRepositoryTests.cs
> +    public async Task GetAll_ReturnsEmptyList()
Why it returns empty list?

2022-11-09 10:41 UTC, nantonov commented on DescriptiveGeometry/Tests/DG.DAL.Tests/DrawingRepositoryTests.cs
> +    public async Task Create_ValidDrawingEntity_ReturnsValidDrawingEntity()
Expected result that entity was created, not returned

2022-11-09 10:41 UTC, nantonov commented on DescriptiveGeometry/Tests/DG.DAL.Tests/DrawingRepositoryTests.cs
> +    public async Task Update_InvalidDrawingEntity_ReturnsException()
Throws, not returns

2022-11-09 10:41 UTC, nantonov commented on DescriptiveGeometry/Tests/DG.DAL.Tests/DrawingRepositoryTests.cs
> +        try
Too complicated

2022-11-09 13:58 UTC, kaallaash commented on DescriptiveGeometry/Tests/DG.DAL.Tests/DrawingRepositoryTests.cs
> +    public async Task GetAll_ReturnsEmptyList()
because I decided to do a useless check

2022-11-14 12:11 UTC, Blackolf931 requested changes

2022-11-14 12:11 UTC, Blackolf931 commented on DescriptiveGeometry/Tests/DG.DAL.IntegrationTests/DrawingRepositoryIntegrationTests.cs
> +    public async Task Create_ValidDrawingEntity_EntityIsCreated(
What about naming? Create_ValidDrawingEntity_ReturnsValidDrawingEntity. Also see all methods

2022-11-14 12:11 UTC, Blackolf931 commented on DescriptiveGeometry/Tests/DG.DAL.IntegrationTests/DrawingRepositoryIntegrationTests.cs
> +        var actualDrawing = await _drawingRepository.GetById(expectedDrawing.Id, default);
it looks strange because we shouldn't add entity with id. In this case you don't get entity, but you use expectedDrawing.Id

2022-11-14 12:11 UTC, Blackolf931 commented on DescriptiveGeometry/Tests/DG.DAL.IntegrationTests/DrawingRepositoryIntegrationTests.cs
> +        actualDrawing.ShouldBe(null);
Can we use ShouldBeNull?

2022-11-14 15:01 UTC, moltenessence approved these changes

2022-11-15 07:58 UTC, Blackolf931 approved these changes

2022-11-15 09:00 UTC, merged