add DrawingController.cs
nantonov/AKD pull request #5
Opened 2022-10-21 13:55 UTC by kaallaash

2022-10-21 14:24 UTC, moltenessence commented on DescriptiveGeometry/DG.API/Controllers/DrawingController.cs
> +            .ConfigureAwait(false);
What are benefits of using 'ConfigureAwait(false)' in controller?

2022-10-24 09:47 UTC, kaallaash commented on DescriptiveGeometry/DG.API/Controllers/DrawingController.cs
> +            .ConfigureAwait(false);
> What are benefits of using 'ConfigureAwait(false)' in controller?
Yes. You're right. It's useless.

2022-10-24 11:08 UTC, nantonov requested changes

2022-10-24 11:08 UTC, nantonov commented on DescriptiveGeometry/DG.API/Controllers/DrawingController.cs
> +    public async Task<ActionResult<Drawing>> Get(
ActionResult for what?

2022-10-24 11:08 UTC, nantonov commented on DescriptiveGeometry/DG.API/Controllers/DrawingController.cs
> +    public async Task<List<Drawing>> FindByDescription(
Why not ActionResult here?

2022-10-24 11:08 UTC, nantonov commented on DescriptiveGeometry/DG.API/Controllers/DrawingController.cs
> +        [FromRoute] string description,
Why FromRoute?

2022-10-24 11:08 UTC, nantonov commented on DescriptiveGeometry/DG.API/Controllers/DrawingController.cs
> +    public async Task<List<Drawing>> GetDrawings(
Why in the name you use Drawings here?
But in the other endpoints you don't use it

2022-10-24 11:08 UTC, nantonov commented on DescriptiveGeometry/DG.API/Controllers/DrawingController.cs
> +    public async Task<List<int>> GetId(
What is the purpose of this endpoint?

2022-10-24 11:08 UTC, nantonov commented on DescriptiveGeometry/DG.API/Controllers/DrawingController.cs
> +    public async Task<List<int>> GetId(
Name doesn't reflect the logic of this endpoint

2022-10-24 11:08 UTC, nantonov commented on DescriptiveGeometry/DG.API/Controllers/DrawingController.cs
> +      [FromBody] Drawing drawing,
In RESTful API you mustn't pass ids through body in PUT method

2022-10-24 13:42 UTC, kaallaash commented on DescriptiveGeometry/DG.API/Controllers/DrawingController.cs
> +        [FromRoute] string description,
> Why FromRoute?
Edit on FromQuery

2022-10-24 14:19 UTC, moltenessence requested changes

2022-10-24 14:19 UTC, moltenessence commented on DescriptiveGeometry/DG.API/Controllers/DrawingController.cs
> +    private static Drawing MapToDrawing(ShortDrawingViewModel drawing)
Try to use automapper

2022-10-24 14:19 UTC, moltenessence commented on DescriptiveGeometry/DG.API/Controllers/DrawingController.cs
> +    public async Task<List<Drawing>> GetAll(
Return ViewModel instead model from BLL

2022-10-24 14:19 UTC, moltenessence commented on DescriptiveGeometry/DG.API/Controllers/DrawingController.cs
> +        return _drawingService.Delete(id, cancellationToken);
Why this method is not async ?

2022-10-24 14:26 UTC, nantonov commented on DescriptiveGeometry/DG.API/Controllers/DrawingController.cs
> +    public async Task<List<Drawing>> FindByDescription(
FindBy or GetBy?

2022-10-24 14:44 UTC, kaallaash commented on DescriptiveGeometry/DG.API/Controllers/DrawingController.cs
> +    private static Drawing MapToDrawing(ShortDrawingViewModel drawing)
It'll be in next PR

2022-10-24 14:49 UTC, nantonov approved these changes

2022-10-24 15:20 UTC, GodlyCat approved these changes

2022-10-24 15:20 UTC, GodlyCat commented on DescriptiveGeometry/DG.API/Controllers/DrawingController.cs
> +    public async Task<List<Drawing>> GetAll(
It'll be in next PR

2022-10-24 15:20 UTC, GodlyCat commented on DescriptiveGeometry/DG.API/Controllers/DrawingController.cs
> +        return _drawingService.Delete(id, cancellationToken);
When we have only one async operation in async method, we could just return this async operation without async/await

2022-10-24 15:27 UTC, merged