add migrations
nantonov/AKD pull request #8
Opened 2022-10-25 09:00 UTC by kaallaash

2022-10-25 09:21 UTC, Blackolf931 approved these changes

2022-10-25 10:57 UTC, nantonov requested changes
Get rid of unnecessary migrations, create 1 clear migration instead

2022-10-25 10:57 UTC, nantonov commented on DescriptiveGeometry/DG.DAL/Entities/DrawingRow.cs
> +    public int DownLoadCount { get; set; }
DownLoad => Download
And use plural form => Download**s**Count

2022-10-25 11:31 UTC, nantonov requested changes

2022-10-25 11:31 UTC, nantonov commented on DescriptiveGeometry/DG.DAL/Registration.cs
> +public static class Registration
Wrong naming 
Registration is an action

2022-10-25 11:31 UTC, nantonov commented on DescriptiveGeometry/DG.DAL/Migrations/DatabaseContextModelSnapshot.cs
> +            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);
Is it needed?

2022-10-25 11:31 UTC, nantonov commented on DescriptiveGeometry/DG.DAL/Migrations/DatabaseContextModelSnapshot.cs
> +                .HasAnnotation("Relational:MaxIdentifierLength", 128);
Is it needed?

2022-10-25 15:17 UTC, kaallaash commented on DescriptiveGeometry/DG.DAL/Migrations/DatabaseContextModelSnapshot.cs
> +            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);
I don't know how I fix it

2022-10-25 15:22 UTC, Blackolf931 approved these changes

2022-10-25 15:24 UTC, nantonov requested changes

2022-10-26 08:10 UTC, kaallaash commented on DescriptiveGeometry/DG.DAL/Context/HistoryRepository.cs
> +internal class HistoryRepository : SqlServerHistoryRepository
Sorry, I was inattentive

2022-10-26 08:20 UTC, moltenessence approved these changes

2022-10-26 08:32 UTC, Blackolf931 approved these changes

2022-10-26 08:57 UTC, nantonov approved these changes

2022-10-26 08:57 UTC, merged